accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import SignUp

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUp.as_view(), name='signup')

]

groups/urls.py
from django.urls import path

from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name='all'),
    path('posts/in/<slug>', views.SingleGroup.as_view(), name='single'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('delete/<slug>/', views.DeleteGroup.as_view(), name='delete'),
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave')
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.ListPosts.as_view(), name='all'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/<int:pk>/', views.SinglePost.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete')
]

star_cloud/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls')),
    path('posts/', include('posts.urls'))

]

accounts/models.py
from django.contrib import auth


# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return '@{}'.format(self.user.username)

groups/models.py
import misaka
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

User = get_user_model()


# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(editable=False, allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, blank=True, default='')
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('groups:all')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

posts/models.py
import misaka
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from groups.models import Group

User = get_user_model()


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.user.username, 'pk': self.pk})

    class Meta:
        ordering = ['-create_at']
        unique_together = ['user', 'group']

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import UserCreateForm


# Create your views here.
class SignUp(CreateView):
    success_url = reverse_lazy('login')
    form_class = UserCreateForm
    template_name = 'accounts/signup.html'

groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic

from .models import Group, GroupMember


# Create your views here.
class ListGroups(generic.ListView):
    model = Group


class SingleGroup(generic.DetailView):
    model = Group


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    model = Group
    fields = ('name', 'description')


class DeleteGroup(LoginRequiredMixin, generic.DeleteView):
    model = Group
    success_url = reverse_lazy('groups:all')


class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except:
            messages.warning(self.request, 'You already in this group')
        else:
            messages.success(self.request, 'You are joined this group')
        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(user=self.request.user, group__slug=self.kwargs.get('slug'))
        except:
            messages.warning(self.request, 'You are not in this group')
        else:
            membership.delete()
            messages.success(self.request, 'You are leaved this group')
        return super().get(request, *args, **kwargs)

posts/views.py
from braces.views import SelectRelatedMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.views import generic

User = get_user_model()
from .models import Post


# Create your views here.
class ListPosts(SelectRelatedMixin, generic.ListView):
    model = Post
    select_related = ['user', 'group']


class UserPosts(generic.ListView):
    model = Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['post_user'] = self.post_user
        return context


class SinglePost(SelectRelatedMixin, generic.DetailView):
    model = Post
    select_related = ['user', 'group']

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    model = Post
    fields = ('message', 'group')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = Post
    select_related = ['user', 'group']
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__id=self.request.user.id)

star_cloud/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'index.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="container">
        <h1>Login</h1>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <hr>

            <input type="submit" class="btn btn-outline-info" value="Login">
            <small class="text-muted"><a href="{% url 'password_reset' %}">Forgot your password?</a></small>

        </form>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="container">
        <h1>Sign Up</h1>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-lg btn-outline-info" value="Sign Up">
        </form>
    </div>
{% endblock %}

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            {% block pregroup %}{% endblock %}
            {% block group_content %}{% endblock %}
            {% block postgroup %}{% endblock %}
        </div>

    </div>
{% endblock %}

groups/templates/groups/group_confirm_delete.html
{% extends 'groups/group_base.html' %}
{% block group_content %}
    <div class="container">
        <h1>Are you sure want to delete {{ object }} group</h1>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="Delete" class="btn btn-danger btn-lg">
            <a href="{% url 'groups:all' %}" class="btn btn-default">Cancel</a>
        </form>
    </div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}
    <div class="container">
        <h1>{{ group.name }}</h1>
        <h2>Members count: {{ group.members.count }}</h2>
        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-warning"><i
                    class="far fa-times-circle"></i>Leave</a>
            <a href="{% url 'groups:delete' slug=group.slug %}" class="btn btn-lg btn-danger"><i
                    class="far fa-trash-alt"></i>Delete</a>
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-warning"><i
                    class="far fa-check-circle"></i>Join</a>
        {% endif %}
    </div>
{% endblock %}
{% block group_content %}
    <div class="col-sm-8">
        {% if group.posts.count == 0 %}
            <h3>No posts in this group yet</h3>
        {% else %}
            {% for post in group.posts.all %}
                {% include 'posts/_posts.html' %}
            {% endfor %}
        {% endif %}

    </div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap4 %}
{% block group_content %}
    <div class="container">
        <h1>Creat new group!</h1>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-lg btn-outline-info">


        </form>

    </div>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}
    <div class="col-sm-4">
        {% if user.is_authenticated %}
            <h2>
                Welcome Back
                <a href="{% url 'posts:for_user' username=user.username %}">@{{ user.username }}</a>
            </h2>
        {% endif %}
        <h2>Groups</h2>
        <p>Welcome to the Groups Page!<br> Select a Group with a shared interest!</p>
        {% if user.is_authenticated %}
            <a href="{% url 'groups:create' %}" class="btn btn-lg btn-warning"><i class="fas fa-plus"></i>Create New
                Group</a>
        {% endif %}


    </div>
{% endblock %}
{% block group_content %}
    <div class="col-sm-8">
        {% for group in group_list %}
            <a href="{% url 'groups:single' slug=group.slug %}"
               class="list-group-item list-group-item-action flex-column align-items-start">
                <h3 class="mb-1">{{ group.name }}</h3>
                <h3 class="mb-1">{{ group.description }}</h3>
                <div class="d-flex w-40 justify-content-between">
                    <small class="text-muted">
                        <span class="badge badge-secondary">{{ group.members.count }}</span>member{{ group.members.count|pluralize }}
                    </small>
                    <small class="text-muted">
                        <span class="badge badge-secondary">{{ group.posts.count }}</span>post{{ group.posts.count|pluralize }}
                    </small>
                    <span></span><span></span>
                </div>
            </a>

        {% endfor %}

    </div>
{% endblock %}

posts/templates/posts/_posts.html
<div class="media-body">
    <h3><a href="{% url 'posts:for_user' username=post.user.username %}">{{ post.user.username }}</a></h3>
    <h3>{{ post.message_html|safe }}
        <time class="time"><a
                href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.create_at }}</a>
        </time>
        {% if post.group %}
            in <a href="{% url 'groups:single' slug=post.group.slug %}">{{ post.group.name }}</a>
        {% endif %}
        <hr>
    </h3>

    <div class="media-footer">
        {% if user.is_authenticated and post.user == user and not hide_delete %}
            <a href="{% url 'posts:delete' pk=post.pk %} " class="btn btn-default">
                <span class="fa fa-remove text-danger" aria-hidden="true"></span>
                <span class="text-danger icon-label">Delete</span>
            </a>
        {% endif %}
    </div>
</div>

posts/templates/posts/post_base.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            {% block prepost %}{% endblock %}
            {% block post_content %}{% endblock %}
            {% block post_post %}{% endblock %}
        </div>

    </div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
    <h1>Are you sure want to delete this post</h1><br>
    <div class="container">
        {% include 'posts/_posts.html' with post=object hide_delete=True %}
    </div>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn-lg btn btn-danger" VALUE="Delete">
        <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-light btn-lg">Cancel</a>
    </form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
    {% include 'posts/_posts.html' %}
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap4 %}
{% block post_content %}
    <div class="container">
        <h1>Creat new post!</h1>
        <form method="post" action="{% url 'posts:create' %}">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-lg btn-outline-info" value="New Post">


        </form>

    </div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
    {% for post in object_list %}
        {% include 'posts/_posts.html' %}
    {% endfor %}

{% endblock %}

posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}
{% block prepost %}
    <div class="col-sm-4">
        <h1>@{{ post_user.username }}</h1>
    </div>
{% endblock %}
{% block post_content %}
    <div class="col-sm-8">
        {% for post in object_list %}
            {% include 'posts/_posts.html' %}
        {% endfor %}

    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Star cloud</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>


    <script src="https://kit.fontawesome.com/21d1bcd9c1.js" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'master.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-dark" role="navigation">
    <div class="container navbar-nav align-items-center">
        <a class="navbar-brand" href="{% url 'home' %}">Star Cloud</a>
        <div class=" navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'posts:create' %}">Posts</a>
                <a class="nav-item nav-link" href="{% url 'groups:all' %}">Groups</a>
                <a class="nav-item nav-link" href="{% url 'groups:create' %}">Create Group</a>
                <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'posts:create' %}">Posts</a>
                <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
            {% endif %}
        </div>

    </div>
</nav>
<div class="container">
    {% block content %}

    {% endblock %}
    <canvas id="canvas"></canvas>
</div>
</body>
<script type="text/javascript" src="{% static 'master.js' %}"></script>
</html>

templates/index.html
{% extends 'base.html' %}